// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRLO5WxqwK5L7r8ODxtwYP9Rap7Gkiz_Y',
    appId: '1:984698263611:ios:7033d1468fdf310e15641e',
    messagingSenderId: '984698263611',
    projectId: 'velo-toulouse-5ae00',
    databaseURL: 'https://velo-toulouse-5ae00-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'velo-toulouse-5ae00.firebasestorage.app',
    iosBundleId: 'com.example.veloToulouse',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvCf4znqpguEsuXMSNENVPdrT501SD92g',
    appId: '1:984698263611:web:ed8a3ec3590858fd15641e',
    messagingSenderId: '984698263611',
    projectId: 'velo-toulouse-5ae00',
    authDomain: 'velo-toulouse-5ae00.firebaseapp.com',
    databaseURL: 'https://velo-toulouse-5ae00-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'velo-toulouse-5ae00.firebasestorage.app',
    measurementId: 'G-E0L4ESTDCN',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRLO5WxqwK5L7r8ODxtwYP9Rap7Gkiz_Y',
    appId: '1:984698263611:ios:7033d1468fdf310e15641e',
    messagingSenderId: '984698263611',
    projectId: 'velo-toulouse-5ae00',
    databaseURL: 'https://velo-toulouse-5ae00-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'velo-toulouse-5ae00.firebasestorage.app',
    iosBundleId: 'com.example.veloToulouse',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjZuIHywh_xdLTY4yWBmvEAuAKhr2IBlU',
    appId: '1:984698263611:android:3338d6d0d465f6f615641e',
    messagingSenderId: '984698263611',
    projectId: 'velo-toulouse-5ae00',
    databaseURL: 'https://velo-toulouse-5ae00-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'velo-toulouse-5ae00.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvCf4znqpguEsuXMSNENVPdrT501SD92g',
    appId: '1:984698263611:web:cd526543ce4eced615641e',
    messagingSenderId: '984698263611',
    projectId: 'velo-toulouse-5ae00',
    authDomain: 'velo-toulouse-5ae00.firebaseapp.com',
    databaseURL: 'https://velo-toulouse-5ae00-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'velo-toulouse-5ae00.firebasestorage.app',
    measurementId: 'G-TSSK1VEF27',
  );

}